# Generated by Django 4.2.7 on 2023-11-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
